### ISSUE TITLE
Importing multi files using path pattern

### ISSUE THREAD

**Issue by LucGranato** [tgreen7/vscode_extension_node_require#15]
This plugin it will be perfect if it was able to require/import multiple files from a glob pattern.

I notice that writing a glob pattern already filters the right files.

![Captura de Tela 2019-07-23 às 18 27 26](https://user-images.githubusercontent.com/4096261/61749045-26ca8c80-ad78-11e9-8f3f-819364a156ba.png)

I think its a good feature request! ;)
Thanks!

**Comment by tgreen7** [comment]
@LucGranato This sounds like a cool idea. I will take a look.

Edit: So i see what you are talking about in terms of the globs bolding the paths, but the quick pick selection still requires you to select a single item and I am unsure how to change that.

**Comment by tgreen7** [comment]
I reworked the quick pick to get the typed string value. I am using micromatch on the label and path of the items in the list. 

I think it works pretty well. It is a little buggy/slow looking if you try to insert a bunch at a time because it needs to do them one by one. I might try to clean that up later.

Let me know if this works for you. Feel free to reopen if there are problems.
